#!/usr/bin/env python

import sys
import luigi.cmdline
import torch.multiprocessing as multiprocessing


if __name__ == "__main__":
    multiprocessing.set_start_method('spawn')
    luigi.cmdline.luigi_run(sys.argv[1:])